services:
#    socialytics.example:
#        class: SocialyticsBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]

    my.oauth_aware.user_provider.service:
        class: SocialyticsBundle\Service\UserProvider
