services:
#    socialytics.example:
#        class: SocialyticsBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    twitter.service:
        class: SocialyticsBundle\Service\TwitterService
        arguments: [%twitter_access_token%, %twitter_token_secret%, %twitter_consumer_key%, %twitter_consumer_secret%]
        
    twitter_metric_factory.service:
        class: SocialyticsBundle\Service\MetricFactory
        arguments: [%twitter_access_token%, %twitter_token_secret%, %twitter_consumer_key%, %twitter_consumer_secret%]
        
    report.service:
        class: SocialyticsBundle\Service\ReportService
        
