security:
    providers:
        in_memory:
            memory: ~
        hwi:                               
            id: hwi_oauth.user.provider  
            
    firewalls:
        secured_area:
            anonymous: ~
            oauth:
                resource_owners:
                    twitter:       "/login/check-twitter"
                login_path:        /login
                use_forward:       false
                failure_path:      /login

                oauth_user_provider:
                    service: hwi_oauth.user.provider.entity
            logout:
                path:   /logout
                target: /

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: IS_AUTHENTICATED_FULLY }