<?php

namespace SocialyticsBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

use \DateTime;

/**
 * Persists Twitter API response for particular date, username and metric.
 *
 * @ORM\Entity
 * @ORM\Table(name="twitter_response")
 * 
 * @author djuro
 */

class TwitterResponse
{
     /**
     * Generated by php uniqid() function.
     * 
     * @ORM\Column(type="string")
     * @ORM\Id
     */
    private $id;
    
    /**
     *
     * @var string
     * @ORM\Column(type="string")
     */
    private $metric;
    
    /**
     *
     * @var DateTime
     * @ORM\Column(type="date")
     */
    private $date;
    
    /**
     *
     * @var string
     * @ORM\Column(type="text")
     */
    private $response;
    
    /**
     *
     * @var int
     * @ORM\Column(type="integer")
     */
    private $page;
    
    /**
     *
     * @var string
     * @ORM\Column(type="string")
     */
    private $username;
    
    
    public function __construct()
    {
        $this->id = uniqid();
    }
    
    function getId() {
        return $this->id;
    }

    function getMetric() {
        return $this->metric;
    }

    function getDate() {
        return $this->date;
    }

    function getResponse() {
        return $this->response;
    }

    function setMetric($metric) {
        $this->metric = $metric;
    }

    function setDate(DateTime $date) {
        $this->date = $date;
    }

    function setResponse($response) {
        $this->response = $response;
    }

    function getUsername() {
        return $this->username;
    }

    function setUsername($username) {
        $this->username = $username;
    }


}
